server {
  listen 80;
  root /usr/share/nginx/html;
  gzip on;
  gzip_types text/css application/javascript image/svg+xml;
  add_header X-Robots-Tag "noindex, nofollow" always;
  location / { try_files $uri $uri/ $uri.html =404; add_header Cache-Control "no-cache"; add_header X-Robots-Tag "noindex, nofollow" always; }
  location /assets/ { add_header Cache-Control "public, max-age=604800"; add_header X-Robots-Tag "noindex, nofollow" always; }
}
